version: "3.0"

services:
  bento-box:
    image: bentorobotics/rosbox:robot-jazzy
    container_name: bento-box-ros
    user: root
    init: true
    restart: always
    privileged: true
    environment:
        - EDU_ROBOT_NAMESPACE=bento
    network_mode: "host"
    volumes:
      - './launch-content:/launch-content:ro'
      - '/dev:/dev'
      - '/run/udev:/run/udev' # libcamera won't work without this
    working_dir: '/launch-content'
    command: 'ros2 launch bento-box.launch.py robot_namespace:="bento_box"'
