version: "3.0"

services:
  bento-box:
    image: bentorobotics/rosbox:robot
    container_name: bento-box-ros
    user: root
    restart: always
    privileged: true
    environment:
        - EDU_ROBOT_NAMESPACE=bento
    network_mode: "host"
    volumes:
      - './launch-content:/launch-content:ro'
      - '/dev:/dev'
      - '/run/udev:/run/udev' # libcamera won't work without this
    command: bash -c 'while true; do cansend can0 580#0241AD347300; sleep 1; done&  ros2 launch /launch-content/bento-box.launch.py robot_namespace:="bento_box"'
