#_______         ____     
#___/ _ )__________/ /_____
#__/ _ )/ -_)/ _ \/ __// _ )
#_/___/ \__//_//_/\__/(___/
#
# /etc/netplan/config.yaml
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    # Jetson built-in Ethernet
    # (Ethernet→CAN board)
    eth0:
      dhcp4: no
      addresses:
        - 192.168.2.200/24
      routes:
        - to: 192.168.2.200
          via: 192.168.2.1
          metric: 100
          on-link: true
    # USB ethernet adapter (optional)
    eth1:
      dhcp4: no
      addresses:
        - 192.168.42.42/24
      routes:
        - to: default
          via: 192.168.42.1
          metric: 100  
          on-link: true
    # Jetson network over USB
    usb0:
      dhcp4: true
  wifis:
    # WiFi AP
    wlan0:
      addresses:
        - 192.168.47.0/24
      access-points:
        "Bento Box":
          password: "BentoBox"
          mode: ap
          band: 2.4GHz
          channel: 9
      dhcp4: true
      dhcp6: false
